name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: eddieJPNG
